In [1]:
def categorize_with_new_rules(description):
    if any(keyword in description for keyword in ["山姆", "水费", "电费", "燃气"]):
        return "Daily Necessities"
    elif any(keyword in description for keyword in ["餐厅", "饭", "食", "饮", "酒", "大众点评", "美团"]):
        return "Dining"
    elif "比斯特" in description:
        return "Clothing"
    elif any(keyword in description for keyword in ["携程", "飞猫", "酒店"]):
        return "Travel"
    elif any(keyword in description for keyword in ["衣", "服", "鞋", "裤"]):
        return "Clothing"
    elif any(keyword in description for keyword in ["电影", "音乐", "娱乐", "游戏"]):
        return "Entertainment"
    elif any(keyword in description for keyword in ["旅游", "机票", "酒店", "旅行"]):
        return "Travel"
    elif any(keyword in description for keyword in ["宠物", "猫", "狗", "宠"]):
        return "Pets"
    else:
        return "Other"

In [2]:
import imaplib
import email
from email.header import decode_header
import re
import json
import requests
import pandas as pd
from bs4 import BeautifulSoup
from datetime import datetime

def send_to_db(payload):
    """
    发送 JSON 数据到后端 API。
    """
    url = "http://www.joelu.cn:20006/api/v1/transactions"
    headers = {
        'accept': 'application/vnd.api+json',
        'Content-Type': 'application/json',
        'Authorization': (
            'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDZiMjJmNGM1ZjIwODUyZGY3ZTVkYTZlNzVkN2RmNGNlYzEwYjk1NDQ5MjIyMGIyNmJlZjRhOWY5NDY0NTE1ZjZhZGE3MmNiNTk2ZWMxNWUiLCJpYXQiOjE3NDE0Mzg5ODQuNTU5NTYsIm5iZiI6MTc0MTQzODk4NC41NTk1NjUsImV4cCI6MTc3Mjk3NDk4Mi41MjA4MTQsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.b7LwG7EnP9OCdwXXlJHVSX8nf-nYd1QhMqdGFbXOb13T1DejwFxyFkS-rJRNEWnbdyjQtBeZspgIiVciPSLUTC5Yf9qq1FVApXnZlzY7J2fV61SR6bmPNPWrgkvqrK0hlv69lhrNUHshIAcVNkuaFuSJDuOTcZQUItsAGYk2kBi--aAX4LljJC4kFND_E-zbOWpBXoDGzJC_9kos6iILW9-MR7JKxHIp8ZKKfZyC78Ira0V-YODfyOzbxlALc1Dy9m5wlkzOGGd2o9RKTyfGnjDlm2yDzbeRDLnkTO5d6d8z9pLMHuXsTyAl6eN_95hEegU7R1uQ7cZ1mmVX39tYxc64S1Cf3VAnIUoerQoCNgUd27eUiIqHZ0DmeyRCcMzHlhp3-RsgfUB--QFed6McOSurUVw-5mMS56AjfzVAZ57-rnwLNmIESfyB8U2gJObXrpDKoqYG5POzOU7p7eStYnP9KADM3_7-TVxHDH4Cs1FOz5ASkrq7i9-6DU9S1815nddsMxVERm6Xqg3w3s_8h5mmP2H1_17Iv5p4D1yU1fxzUKLfs_yRpGeO1b5qASkJbhbwbTg2ywUnnFsNxJdT9xF1V1sODnKqqvwekC3xfve53Rf-Lh9uOTaNsPRyHoi0rq4FxocKAc0S_-igewln5nW3mWAWsaDheI1NPzDEdTI'
        )
    }

    response = requests.post(url, headers=headers, data=payload)
    print("API response:", response.status_code, response.text)

def login_to_email(username, password, imap_server):
    """
    Logs in to the email account and returns the connection object.
    """
    try:
        mail = imaplib.IMAP4_SSL(imap_server)
        mail.login(username, password)
        print("登录成功")
        return mail
    except Exception as e:
        print(f"登录失败: {e}")
        return None

def extract_table_from_html_to_dataframe(html_content):
    """
    Extracts table content from the HTML email body and converts it to a DataFrame.
    """
    try:
        soup = BeautifulSoup(html_content, "html.parser")
        tables = soup.find_all("table")
        if not tables:
            print("No tables found in the email content.")
            return None

        # Assuming the first table is the target table
        target_table = tables[0]
        rows = target_table.find_all("tr")

        # Extract headers
        headers = [cell.get_text(strip=True) for cell in rows[0].find_all(["th", "td"])]

        # Extract data rows
        data = []
        for row in rows[1:]:
            cells = row.find_all(["td", "th"])
            row_data = [cell.get_text(strip=True) for cell in cells]
            data.append(row_data)

        # Convert to DataFrame
        df = pd.DataFrame(data, columns=headers)
        return df
    except Exception as e:
        print(f"Failed to extract table: {e}")
        return None

def decode_chinese_text(text_bytes, encodings=['utf-8', 'gb2312', 'gbk', 'gb18030']):
    """
    Try multiple encodings to decode Chinese text.
    """
    if isinstance(text_bytes, str):
        return text_bytes

    for encoding in encodings:
        try:
            return text_bytes.decode(encoding)
        except UnicodeDecodeError:
            continue

    # If all fails, use replace to avoid errors
    return text_bytes.decode('utf-8', errors='replace')

def find_and_process_cmb_credit_card_statements(mail, folder="INBOX", from_email=None, since_date='1-JAN-2025'):
    """
    Fetches emails from the specified folder, filters by subject, and returns the raw HTML content and email date.
    """
    try:
        mail.select(folder)  # Select the folder

        # Search for emails since 1-Feb-2025
        status, messages = mail.search(None, f"SINCE {since_date}")
        if status != "OK":
            print("No messages found.")
            return None, None

        email_ids = messages[0].split()
        print(f"Found {len(email_ids)} total emails in {folder}")

        # Process emails in reverse order (newest first)
        email_ids = list(reversed(email_ids))
        matching_emails = []
        target_subjects = ["中国建设银行信用卡电子账单"]

        for email_id in email_ids:
            res, msg = mail.fetch(email_id, "(BODY[HEADER.FIELDS (SUBJECT FROM DATE)])")
            if res != "OK":
                print(f"Failed to fetch email header ID {email_id}")
                continue

            header_data = msg[0][1]
            header_str = decode_chinese_text(header_data)
            subject_line = [line for line in header_str.split('\r\n') if line.startswith('Subject:')]
            from_line = [line for line in header_str.split('\r\n') if line.startswith('From:')]

            should_process = False
            if subject_line:
                encoded_subject = subject_line[0].replace('Subject:', '').strip()
                try:
                    decoded_parts = decode_header(encoded_subject)
                    subject = ""
                    for part, charset in decoded_parts:
                        if isinstance(part, bytes):
                            if charset:
                                try:
                                    subject += part.decode(charset)
                                except:
                                    subject += decode_chinese_text(part)
                            else:
                                subject += decode_chinese_text(part)
                        else:
                            subject += part
                except:
                    subject = encoded_subject

                for target in target_subjects:
                    if target in subject:
                        should_process = True
                        break

            # Additional filtering by sender if from_email is provided
            if from_email and from_line:
                sender = from_line[0].replace('From:', '').strip()
                if from_email not in sender:
                    should_process = False

            if should_process:
                matching_emails.append(email_id)

        print(f"Found {len(matching_emails)} matching emails")
        html_content_list = []
        # Process the first matching email
        for email_id in matching_emails:
            res, msg = mail.fetch(email_id, "(RFC822)")
            if res != "OK":
                print(f"Failed to fetch full email ID {email_id}")
                continue

            for response in msg:
                if isinstance(response, tuple):
                    msg_obj = email.message_from_bytes(response[1])

                    # Decode email subject
                    subject_bytes, encoding = decode_header(msg_obj["Subject"])[0]
                    if isinstance(subject_bytes, bytes):
                        subject = decode_chinese_text(subject_bytes)
                    else:
                        subject = subject_bytes
                    print("邮件标题:", subject)

                    # Sender and Date
                    from_ = msg_obj.get("From")
                    date = msg_obj.get("Date")
                    print("发件人:", from_)
                    print("日期:", date)

                    # Extract HTML content
                    html_content = None
                    if msg_obj.is_multipart():
                        for part in msg_obj.walk():
                            if part.get_content_type() == 'text/html':
                                payload = part.get_payload(decode=True)
                                charset = part.get_content_charset() or 'utf-8'
                                html_content = payload.decode(charset, errors='ignore')
                                break
                    else:
                        if msg_obj.get_content_type() == 'text/html':
                            payload = msg_obj.get_payload(decode=True)
                            charset = msg_obj.get_content_charset() or 'utf-8'
                            html_content = payload.decode(charset, errors='ignore')

                    if html_content is None:
                        print("未找到HTML正文内容。")
                        # return None, None
                    html_content_list.append(html_content)
        return html_content_list,date
                    # Optionally, you can extract table data here for debugging:
                    # soup = BeautifulSoup(html_content, 'html.parser')
                    # tables = soup.find_all('table')
                    # if tables:
                    #     print(f"HTML中发现了 {len(tables)} 个表格")
                    #     df_preview = pd.read_html(str(tables[0]))[0]
                    #     print("提取到表格数据（前5行）：\n", df_preview.head())
                    # else:
                    #     print("未发现HTML表格。")
                    #
                    # return html_content, date

        # If no matching email processed, return None
        # return None, None

    except Exception as e:
        print(f"获取邮件内容失败: {e}")
        return None, None

def logout_from_email(mail):
    """
    Logs out from the email account.
    """
    try:
        mail.logout()
        print("已退出邮箱")
    except Exception as e:
        print(f"Failed to logout: {e}")

def parse_html_to_df(html: str, bill_date: str) -> pd.DataFrame:
    """
    解析 HTML，过滤出最后一列为 "CN" 的行并根据指定的 bill_date 处理日期；
    最终返回一个包含 date, amount, description, category 列的 DataFrame。
    """
    # 1) 解析 HTML
    soup = BeautifulSoup(html, 'html.parser')
    tables = soup.find_all("table")
    return soup
    print(f"解析到 {len(tables)} 个表格。")
    for idx, table in enumerate(tables):
        print(f"\n表格 {idx} 原始内容：")
        print(table.prettify())

    # 2) 收集每个 <tr> 中的所有 <td> 文本，跳过表头
    td_texts = []
    for tr in soup.find_all("tr")[1:]:  # Skip the header row
        cells = [td.get_text(strip=True) for td in tr.find_all("td")]
        if cells:
            td_texts.append(cells)

    # 3) 只保留最后一列是 "CN" 的行
    transcript = [row for row in td_texts if len(row) > 0 and row[-1] == "CN"]

    # 4) 假设表格中有 8 列，取从第 2 列到第 8 列，再过滤掉不满足长度要求的行
    transcript = [row[1:] for row in transcript if len(row) == 8]

    # 5) 处理 bill_date，使之能被 strptime 解析（去掉多余的 (CST) 等）
    bill_date_clean = re.sub(r"\s*\(.*\)$", "", bill_date)
    try:
        bill_date_dt = datetime.strptime(bill_date_clean, "%a, %d %b %Y %H:%M:%S %z")
    except ValueError:
        try:
            bill_date_dt = datetime.strptime(bill_date_clean, "%a, %d %b %Y %H:%M:%S")
        except ValueError:
            print(f"Could not parse date: {bill_date_clean}, using current date")
            bill_date_dt = datetime.now()

    # 将带时区的日期转换为 naive 日期
    bill_date_naive = bill_date_dt.replace(tzinfo=None)

    # 6) 遍历行，组装数据
    data = []
    for row in transcript:
        try:
            # row[0] 为月日 (MMDD)
            date_temp = datetime.strptime(row[0], "%m%d").replace(year=datetime.now().year)
            # 如果解析出来的日期晚于账单日期，则说明属于去年
            if date_temp > bill_date_naive:
                date_temp = date_temp.replace(year=date_temp.year - 1)
            date_str = date_temp.strftime("%Y-%m-%d")

            # row[3] 是金额, 如 ¥1,000
            amount_str = row[3].replace('¥', '').replace('\xa0', '').replace(',', '')
            amount = float(amount_str)

            description = row[2]
            category = ""  # 如果需要分类逻辑，可以后续补充

            data.append([date_str, amount, description, category])
        except Exception as e:
            print(f"Error processing row {row}: {e}")

    # 7) 生成 DataFrame
    df = pd.DataFrame(data, columns=["date", "amount", "description", "category"])
    return df

def send_to_db(payload):
    """
    发送 JSON 数据到后端 API。
    """
    url = "http://www.joelu.cn:20006/api/v1/transactions"
    headers = {
        'accept': 'application/vnd.api+json',
        'Content-Type': 'application/json',
        'Authorization': (
            'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJhdWQiOiIxIiwianRpIjoiNDZiMjJmNGM1ZjIwODUyZGY3ZTVkYTZlNzVkN2RmNGNlYzEwYjk1NDQ5MjIyMGIyNmJlZjRhOWY5NDY0NTE1ZjZhZGE3MmNiNTk2ZWMxNWUiLCJpYXQiOjE3NDE0Mzg5ODQuNTU5NTYsIm5iZiI6MTc0MTQzODk4NC41NTk1NjUsImV4cCI6MTc3Mjk3NDk4Mi41MjA4MTQsInN1YiI6IjEiLCJzY29wZXMiOltdfQ.b7LwG7EnP9OCdwXXlJHVSX8nf-nYd1QhMqdGFbXOb13T1DejwFxyFkS-rJRNEWnbdyjQtBeZspgIiVciPSLUTC5Yf9qq1FVApXnZlzY7J2fV61SR6bmPNPWrgkvqrK0hlv69lhrNUHshIAcVNkuaFuSJDuOTcZQUItsAGYk2kBi--aAX4LljJC4kFND_E-zbOWpBXoDGzJC_9kos6iILW9-MR7JKxHIp8ZKKfZyC78Ira0V-YODfyOzbxlALc1Dy9m5wlkzOGGd2o9RKTyfGnjDlm2yDzbeRDLnkTO5d6d8z9pLMHuXsTyAl6eN_95hEegU7R1uQ7cZ1mmVX39tYxc64S1Cf3VAnIUoerQoCNgUd27eUiIqHZ0DmeyRCcMzHlhp3-RsgfUB--QFed6McOSurUVw-5mMS56AjfzVAZ57-rnwLNmIESfyB8U2gJObXrpDKoqYG5POzOU7p7eStYnP9KADM3_7-TVxHDH4Cs1FOz5ASkrq7i9-6DU9S1815nddsMxVERm6Xqg3w3s_8h5mmP2H1_17Iv5p4D1yU1fxzUKLfs_yRpGeO1b5qASkJbhbwbTg2ywUnnFsNxJdT9xF1V1sODnKqqvwekC3xfve53Rf-Lh9uOTaNsPRyHoi0rq4FxocKAc0S_-igewln5nW3mWAWsaDheI1NPzDEdTI'
        )
    }

    response = requests.post(url, headers=headers, data=payload)
    print("API response:", response.status_code, response.text)
def parse_transaction_details_table(html: str) -> pd.DataFrame:
    """
    使用 pandas.read_html 解析邮件中的所有表格，并筛选出含有交易明细的表格，
    该表格应包含“交易日”、“银行记账日”、“卡号后四位”、“交易描述”等字段。
    """
    try:
        # 使用 bs4 解析，获得所有的表格
        tables = pd.read_html(html, flavor="bs4")
        print(f"共提取到 {len(tables)} 个表格。")
        for idx, df in enumerate(tables):
            print(f"\n表格 {idx} 的前5行预览：")
            print(df.head())

        # 筛选出可能包含“交易日”字段的表格
        transaction_table = None
        for df in tables:
            # 检查任一列标题是否包含“交易日”
            if any("交易日" in str(col) for col in df.columns):
                transaction_table = df
                break

        if transaction_table is not None:
            print("找到交易明细表：")
            print(transaction_table.head())
            return transaction_table
        else:
            print("未找到包含‘交易日’字段的交易明细表。")
            return None

    except Exception as e:
        print(f"解析交易明细表时出错: {e}")
        return None

def parse_transaction_details_table(html: str) -> pd.DataFrame:
    """
    解析HTML内容中【交易明细】部分的表格，
    通过提取每个<tr>和<td>/<th>的文本信息构建DataFrame。
    先查找包含“交易日”关键字的表格作为目标表，
    然后对目标表中的每一行提取所有单元格文本。
    """
    soup = BeautifulSoup(html, "html.parser")
    candidate_tables = []
    # 查找所有表格，筛选包含“交易日”文本的表格
    tables = soup.find_all("table")
    for table in tables:
        if table.find(string=re.compile("交易日")):
            candidate_tables.append(table)

    if not candidate_tables:
        print("未找到包含交易明细的表格。")
        return None

    # 选取候选中行数最多的表格作为目标表
    target_table = max(candidate_tables, key=lambda t: len(t.find_all("tr")))
    print("找到目标交易明细表，共 {} 行".format(len(target_table.find_all("tr"))))

    # 遍历目标表的每一行，提取所有单元格（td或th）的文本
    rows = []
    for tr in target_table.find_all("tr"):
        cells = tr.find_all(["td", "th"])
        if not cells:
            continue
        row = [cell.get_text(strip=True) for cell in cells]
        rows.append(row)

    if not rows:
        print("未提取到任何行数据。")
        return None

    idx_start= rows.index(['交易日', '银行记账日', '卡号后四位', '交易描述', '交易币/金额', '结算币/金额'])
    idx_end = rows.index(['*** 结束 The End ***'])
    # sub_rows = _[idx_start:idx_end]
    sub_rows = [row for row in rows[idx_start:idx_end] if len(row) == 8]
    df = pd.DataFrame(sub_rows[1:], columns=['交易日', '银行记账日', '卡号后四位', '交易描述', '货币a','交易币/金额', '货币a', '结算币/金额'])
    return df

def process_df(df):
    payload_list = []
    for idx, row in df.iterrows():
        payload = json.dumps({
          "error_if_duplicate_hash": False,
          "apply_rules": False,
          "fire_webhooks": True,
          "transactions": [
            {
              "type": "withdrawal",
              "date": row["交易日"],
              "amount": row["结算币/金额"],
              "description": row["交易描述"],
              "currency_code": "CNY",
              "budget_id": "",
              "category_id": "",
              "category_name": categorize_with_new_rules(row["交易描述"]),
              "source_name": "家庭支出",
              "tags": None,
              "notes": ""
            }
          ]
        })
        print(payload)
        send_to_db(payload)

# Main execution
username = "214332567@qq.com"  # 替换为你的QQ邮箱
password = "esxipifovvowcbaj"
imap_server = "imap.qq.com"
mail = login_to_email(username, password, imap_server)

if mail:
    html_content_list, date = find_and_process_cmb_credit_card_statements(mail, since_date='SINCE 1-MAR-2025')
    for html_content in html_content_list:
        df = parse_transaction_details_table(html_content)
        process_df(df)
    logout_from_email(mail)

登录成功
Found 3431 total emails in INBOX
获取邮件内容失败: command: FETCH => socket error: EOF

TypeError: 'NoneType' object is not iterable

In [24]:
# bill_date = datetime.datetime(2024,12,15).strftime("%Y-%m-%d")

2

In [48]:


    # 判断是否存在标题行：检查第一行是否包含常见关键词
    # header_keywords = ["交易日", "银行记账日", "卡号后四位", "交易描述"]
    # header = rows[0]
    # if any(keyword in header for keyword in header_keywords):
    #     df = pd.DataFrame(rows[1:], columns=rows[0])
    # else:
    #     df = pd.DataFrame(rows)
    #
    # return df

# 示例用法：
# df_transaction = parse_transaction_details_table(html_content)
# if df_transaction is not None:
#     print("提取到的交易明细表：")
#     print(df_transaction.head())
html_content = html_content_list[1]
df = parse_transaction_details_table(html_content)

找到目标交易明细表，共 182 行

In [49]:
# !pip install html5lib

In [50]:
df

,交易日,银行记账日,卡号后四位,交易描述,货币a,交易币/金额,货币a,结算币/金额
0,2024-12-11,2024-12-12,3821,财付通-财付通,CNY,"-1,102.00",CNY,"-1,102.00"
1,2024-12-13,2024-12-14,3821,网银在线-京东商城业务,CNY,348.98,CNY,348.98
2,2024-12-14,2024-12-14,3821,财付通-上海阿新餐饮有限公司,CNY,253.00,CNY,253.00
3,2024-12-14,2024-12-15,3821,网银在线-网银在线（北京）科技有限公司,CNY,-315.12,CNY,-315.12
4,2024-12-14,2024-12-15,3821,网银在线-物择宠物生活专营店,CNY,205.98,CNY,205.98
...,...,...,...,...,...,...,...,...
113,2025-01-09,2025-01-09,6121,滴滴支付-滴滴出行快车,CNY,13.90,CNY,13.90
114,2025-01-09,2025-01-09,6121,滴滴支付-滴滴出行快车,CNY,12.00,CNY,12.00
115,2025-01-09,2025-01-09,6121,财付通-LAWSON,CNY,6.97,CNY,6.97
116,2025-01-09,2025-01-09,6121,财付通-禛品生活,CNY,6.00,CNY,6.00
117,2025-01-09,2025-01-09,6121,支付宝-上海拉扎斯信息科技有限公司,CNY,86.90,CNY,86.90

,交易日,银行记账日,卡号后四位,交易描述,货币a,交易币/金额,货币a,结算币/金额
0,2024-12-11,2024-12-12,3821,财付通-财付通,CNY,"-1,102.00",CNY,"-1,102.00"
1,2024-12-13,2024-12-14,3821,网银在线-京东商城业务,CNY,348.98,CNY,348.98
2,2024-12-14,2024-12-14,3821,财付通-上海阿新餐饮有限公司,CNY,253.00,CNY,253.00
3,2024-12-14,2024-12-15,3821,网银在线-网银在线（北京）科技有限公司,CNY,-315.12,CNY,-315.12
4,2024-12-14,2024-12-15,3821,网银在线-物择宠物生活专营店,CNY,205.98,CNY,205.98
...,...,...,...,...,...,...,...,...
113,2025-01-09,2025-01-09,6121,滴滴支付-滴滴出行快车,CNY,13.90,CNY,13.90
114,2025-01-09,2025-01-09,6121,滴滴支付-滴滴出行快车,CNY,12.00,CNY,12.00
115,2025-01-09,2025-01-09,6121,财付通-LAWSON,CNY,6.97,CNY,6.97
116,2025-01-09,2025-01-09,6121,财付通-禛品生活,CNY,6.00,CNY,6.00
117,2025-01-09,2025-01-09,6121,支付宝-上海拉扎斯信息科技有限公司,CNY,86.90,CNY,86.90